version: '2'

services:
  sp:
    restart: always
    container_name: djangosaml2idp_sp
    build: sp
    stdin_open: true
    tty: true
    volumes:
      - ./sp:/app
    working_dir: /app
    ports:
      - "8001:8001"

  idp:
    restart: always
    container_name: djangosaml2idp_idp
    build: idp
    stdin_open: true
    tty: true
    volumes:
      - ..:/app
    working_dir: /app/example_setup/idp
    ports:
      - "9000:9000"
